name: Sync To Gitee

on: [push, delete, create]

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
              with:
                source-repo: https://github.com/HaoDong108/DouyinBarrageGrab.git
                destination-repo: https://gitee.com/haodong108/dy-barrage-grab.git