name: Sync To Gitee

on: [push, delete, create]

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee
              uses: zcong1993/actions-git-mirror@master
              with:
                dest-repo: https://gitee.com/haodong108/dy-barrage-grab.git
                dest-token: ${{ secrets.GITEE_PRIVATE_KEY }}
                repo-token: ${{ secrets.GITEE_TOKEN }}